### ISSUE TITLE
Manual bot disconnect detection 

### ISSUE THREAD

**Issue by awmie** [awmie/tishmish#1]
Is there any way to check/detect if a user disconnected the bot manually (By right-clicking > disconnect on the bot in the voice channel)?
(using the same nextcord module/ or any other)

<img width="304" alt="Screenshot 2022-09-28 at 6 16 53 PM" src="https://user-images.githubusercontent.com/95137415/202995338-839efa05-ce64-49e7-b412-d39b764d3d09.png">

basically, when the bot is disconnected manually it should also disconnect from the vc (at the backend) as it still works after disconnecting from the voice channel.

https://user-images.githubusercontent.com/95137415/202996624-13dccc6c-4008-40bc-978f-7a6d5bdb9d09.mp4

**Comment by GeoffreyFClark** [comment]
There doesn't seem to be anything in the Discord API for this exact disconnect button, but I created a pull request involving a convenient auto-disconnect feature when everyone eventually leaves the voice channel. 

This may not directly address the issue of users right-clicking disconnect menu option in Discord, but it does address the underlying reason of why users would ever be motivated to click that button in the first place, thereby deterring the problem from occurring.

Additionally, a further work-around could be an @bot.event that checks if the bot is no longer in a voice channel and if so, await vc.disconnect(force=True), being a catch-all that includes the result of a user manually clicking the aforementioned `disconnect` button in Discord.

**Comment by awmie** [comment]
Thank you, sir, for resolving my problem and contributing to my work.

**Comment by awmie** [comment]
here's the final fix - 
```
@bot.event
async def on_voice_state_update(member, before, after):
    if before.channel is not None and (bot.user in before.channel.members and len(before.channel.members) == 1) or (member.id == bot.user.id and after.channel is None):
        for vc in bot.voice_clients:
            if vc.channel == before.channel:
                await vc.stop()
                await vc.resume()
                await vc.disconnect(force=True)
                break 
```
